parameters:
    database_host:     localhost
    database_name:     products
    database_user:     user
    database_password: passw

    doctrine:
        dbal:
            driver:   pdo_mysql
            host:     '%database_host%'
            dbname:   '%database_name%'
            user:     '%database_user%'
            password: '%database_password%'